### ISSUE TITLE
TODO - fast

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/probeplanner#1]
# fixes
highlight brain regions
clean up messy code

# new functionality
- [x] CLI: there sholld be a command line interface for this
- [x] allen CCF to bregma
- [ ] save set up to file?

# essentials
- [x] setup.py: make sure it's complete
- [ ] tests
- [ ] github actions
- [x] docs: more detailed documentation
- [x] release on PyPI

**Comment by FedeClaudi** [comment]
Also see: https://github.com/brainglobe/bg-atlasapi/issues/99
